### ISSUE TITLE
Vaka-2 -- Wrong Answer

### ISSUE THREAD

**Issue by mervekocagoz** [mustafakocatepe/LogiverseCaseStudy#2]
@mustafakocatepe, 

Aşağıdaki input için deneme yapıldığında hatalı sonuc elde edilmiştir.

**INPUT:**
["Robot","step","getPos","getDir","step","getPos","getDir","step","getPos","getDir", "step","getPos","getDir","step","getPos","getDir", "step","getPos","getDir","step","getPos","getDir"]
[[4,10],[7],[],[],[13],[],[],[935],[],[],[8547],[],[],[57089],[],[],[24587],[],[],[100000],[],[]]

**KODDAN GELEN ÇIKTI:**
[null,null,[3,4],"North",null,[0,4],"South",null,[0,5],"South",null,[3,8],"North",null,[3,0],"East",null,[0,5],"South",null,[3,8],"North"]

**BEKLENEN ÇIKTI:**
[null,null,[3,4],"North",null,[0,4],"South",null,[0,5],"South",null,[0,2],"South",null,[0,9],"West",null,[2,0],"East",null,[0,6],"South"]

**Comment by mustafakocatepe** [comment]
Case çalışması dökümantasyonunda dikkat edilecek noktalar arasında robotun "Tek seferde maximum 1000 adım atabilir." maddesine karşılık 1000'den fazla adım atılmaya çalışıldığında o adım sayısını 1000 olarak kabul ederek işleme devam ettim (39. satır). Ve koddan gelen çıktının bu noktada doğru olduğunu düşünüyorum. 

Bu maddeyi göz ardı edersek ve 39. satırı silersek sizin tarafınızdan beklenen sonuç ve program çıktısı aynı sonucu vermektedir.

![Screenshot_2](https://user-images.githubusercontent.com/7917266/183282714-dafbad75-6ec5-49b8-9ffb-da6a881a7763.png)

**Comment by mervekocagoz** [comment]
@mustafakocatepe , gönderdiğimiz case'in metnini yeniden kontrol ettim. Dediğin gibi, sana gönderilen case versiyonunda, 1.000 olarak sınırladırılmış. Eline sağlık.
